version: '3'
services:
  go:
    build:
      context: .
    volumes:
      - ./:/go/src
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf